#server.port=${SERVER_PORT:8081}
#management.endpoints.web.exposure.include=*
#management.endpoints.enabled-by-default=true
#spring.data.mongodb.host= ${MONGO_HOST:mongo}
#spring.data.mongodb.port= ${MONGO_PORT:27017}
#
#spring.data.elasticsearch.rest.uris = http://${ELASTICSEARCH_HOST:localhost}:9200
#spring.data.elasticsearch.rest.password = changeme
#spring.data.elasticsearch.rest.username = elastic


server:
  port: ${SERVER_PORT:8081}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}    elasticsearch:
      cluster-node: localhost:9200
      client:
        reactive: 
          password: changeme
          username: elastic
      repositories:        enabled: true
     
